version: '3.9'

services:
  app:
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
      - gemconfig:/root/.local/share/gem
    ports:
      - "3000:3000"
    command: "rackup --port 3000 --host 0.0.0.0 --server puma server.ru"

  postgres:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  redis:
    image: redis

volumes:
  pg_data:
  rubygems:
  gemconfig:
