version: '3.9'

services:
  app:
    image: ruby
    working_dir: /app
    container_name: sinatra_app
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
      - gemconfig:/root/.local/share/gem
    ports:
      - "3000:3000"
    command: "puma --port 3000 --bind tcp://0.0.0.0 --threads 0:5 server.ru"
    environment:
      WEB_CONCURRENCY: 1

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis

volumes:
  pg_data:
  rubygems:
  gemconfig:
